on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Maven Package without tests
      run: mvn package -DskipTests

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: rbtn110
        password: Rlarbtn135!

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./store
        push: true
        tags: projectname:latest
        